# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentinelle/sentinelle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentinelle/sentinelle.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1bsentinelle/sentinelle.proto\"\x19\n\tArguments\x12\x0c\n\x04list\x18\x01 \x03(\t\")\n\nTestResult\x12\n\n\x02ok\x18\x01 \x02(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t28\n\nSentinelle\x12*\n\rGetTestResult\x12\n.Arguments\x1a\x0b.TestResult\"\x00'
)




_ARGUMENTS = _descriptor.Descriptor(
  name='Arguments',
  full_name='Arguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='Arguments.list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=56,
)


_TESTRESULT = _descriptor.Descriptor(
  name='TestResult',
  full_name='TestResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='TestResult.ok', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='TestResult.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['Arguments'] = _ARGUMENTS
DESCRIPTOR.message_types_by_name['TestResult'] = _TESTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Arguments = _reflection.GeneratedProtocolMessageType('Arguments', (_message.Message,), {
  'DESCRIPTOR' : _ARGUMENTS,
  '__module__' : 'sentinelle.sentinelle_pb2'
  # @@protoc_insertion_point(class_scope:Arguments)
  })
_sym_db.RegisterMessage(Arguments)

TestResult = _reflection.GeneratedProtocolMessageType('TestResult', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESULT,
  '__module__' : 'sentinelle.sentinelle_pb2'
  # @@protoc_insertion_point(class_scope:TestResult)
  })
_sym_db.RegisterMessage(TestResult)



_SENTINELLE = _descriptor.ServiceDescriptor(
  name='Sentinelle',
  full_name='Sentinelle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTestResult',
    full_name='Sentinelle.GetTestResult',
    index=0,
    containing_service=None,
    input_type=_ARGUMENTS,
    output_type=_TESTRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENTINELLE)

DESCRIPTOR.services_by_name['Sentinelle'] = _SENTINELLE

# @@protoc_insertion_point(module_scope)
